from django.core.management.base import BaseCommand

from listings.models import Property

SEED = [
    {
        "title": "Villa contemporaine",
        "type": "À vendre",
        "price": "2 350 000 TND",
        "location": "La Marsa",
        "details": "420 m² · S+5 · Piscine",
        "reference": "IC-2026-002",
        "image_url": "https://picsum.photos/seed/IC-2026-002/1200/800",
        "status": "Disponible",
        "lat": 36.8667,
        "lng": 10.3167,
        "area": 420,
        "rooms": 6,
        "bedrooms": 5,
        "bathrooms": 4,
        "floor": "Rez-de-chaussée",
        "orientation": "Sud-Est",
        "years": "Moins d'un an",
        "floor_type": "Marbre",
        "features": ["Piscine", "Garage", "Jardin", "Climatisation", "Chauffage central"],
    },
    {
        "title": "Appartement S+3 lumineux",
        "type": "À vendre",
        "price": "580 000 TND",
        "location": "Menzah 9",
        "details": "165 m² · S+3",
        "reference": "IC-2026-001",
        "image_url": "https://picsum.photos/seed/IC-2026-001/1200/800",
        "status": "Disponible",
        "lat": 36.8,
        "lng": 10.2,
        "area": 165,
        "rooms": 4,
        "bedrooms": 3,
        "bathrooms": 2,
        "floor": "3ème",
        "orientation": "Est",
        "years": "Moins d'un an",
        "floor_type": "Parquet",
        "features": ["Balcon", "Climatisation", "Ascenseur", "Garage"],
    },
    {
        "title": "Résidence premium",
        "type": "À louer",
        "price": "2 400 TND / mois",
        "location": "Lac 2",
        "details": "145 m² · S+3",
        "reference": "IC-2026-003",
        "image_url": "https://picsum.photos/seed/IC-2026-003/1200/800",
        "status": "Disponible",
        "lat": 36.82,
        "lng": 10.18,
        "area": 145,
        "rooms": 4,
        "bedrooms": 3,
        "bathrooms": 2,
        "floor": "2ème",
        "orientation": "Ouest",
        "years": "1-5 ans",
        "floor_type": "Carrelage",
        "features": ["Concierge", "Piscine", "Parking"],
    },
    {
        "title": "Penthouse vue mer",
        "type": "À vendre",
        "price": "3 500 000 TND",
        "location": "Carthage",
        "details": "550 m² · S+7 · Terrasse panoramique",
        "reference": "IC-2026-004",
        "image_url": "https://picsum.photos/seed/IC-2026-004/1200/800",
        "status": "Disponible",
        "lat": 36.8611,
        "lng": 10.3269,
        "area": 550,
        "rooms": 8,
        "bedrooms": 7,
        "bathrooms": 5,
        "floor": "Dernier étage",
        "orientation": "Sud",
        "years": "Moins d'un an",
        "floor_type": "Marbre",
        "features": ["Terrasse panoramique", "Ascenseur privé", "Piscine"],
    },
    {
        "title": "Studio moderne centre-ville",
        "type": "À louer",
        "price": "650 TND / mois",
        "location": "Tunis (centre)",
        "details": "55 m² · S+1",
        "reference": "IC-2026-005",
        "image_url": "https://picsum.photos/seed/IC-2026-005/1200/800",
        "status": "Disponible",
        "lat": 36.8,
        "lng": 10.18,
        "area": 55,
        "rooms": 2,
        "bedrooms": 1,
        "bathrooms": 1,
        "floor": "1er",
        "orientation": "Nord",
        "years": "1-5 ans",
        "floor_type": "Parquet",
        "features": ["Balcon", "Climatisation"],
    },
    {
        "title": "Maison de caractère",
        "type": "À vendre",
        "price": "1 200 000 TND",
        "location": "Mutuelleville",
        "details": "320 m² · S+4 · Jardin",
        "reference": "IC-2026-006",
        "image_url": "https://picsum.photos/seed/IC-2026-006/1200/800",
        "status": "Disponible",
        "lat": 36.82,
        "lng": 10.22,
        "area": 320,
        "rooms": 6,
        "bedrooms": 4,
        "bathrooms": 3,
        "floor": "Maison",
        "orientation": "Sud-Ouest",
        "years": "6-10 ans",
        "floor_type": "Marbre",
        "features": ["Jardin", "Garage", "Cheminée"],
    },
    {
        "title": "Duplex spacieux",
        "type": "À louer",
        "price": "1 800 TND / mois",
        "location": "Ariana",
        "details": "240 m² · S+4 + S+2",
        "reference": "IC-2026-007",
        "image_url": "https://picsum.photos/seed/IC-2026-007/1200/800",
        "status": "Disponible",
        "lat": 36.8667,
        "lng": 10.1833,
        "area": 240,
        "rooms": 6,
        "bedrooms": 4,
        "bathrooms": 3,
        "floor": "2 niveaux",
        "orientation": "Est",
        "years": "1-5 ans",
        "floor_type": "Carrelage",
        "features": ["Terrasse", "Garage", "Climatisation"],
    },
    {
        "title": "Appartement de luxe",
        "type": "À vendre",
        "price": "950 000 TND",
        "location": "Lac 1",
        "details": "200 m² · S+3 · Ascenseur privé",
        "reference": "IC-2026-008",
        "image_url": "https://picsum.photos/seed/IC-2026-008/1200/800",
        "status": "Disponible",
        "lat": 36.83,
        "lng": 10.19,
        "area": 200,
        "rooms": 4,
        "bedrooms": 3,
        "bathrooms": 3,
        "floor": "4ème",
        "orientation": "Sud-Est",
        "years": "Moins d'un an",
        "floor_type": "Parquet",
        "features": ["Ascenseur privé", "Garage", "Sécurité"],
    },
    {
        "title": "Terrain premium",
        "type": "À vendre",
        "price": "800 000 TND",
        "location": "Soukra",
        "details": "800 m² · Zone résidentielle",
        "reference": "IC-2026-009",
        "image_url": "https://picsum.photos/seed/IC-2026-009/1200/800",
        "status": "Disponible",
        "lat": 36.8,
        "lng": 10.15,
        "area": 800,
        "rooms": 0,
        "bedrooms": 0,
        "bathrooms": 0,
        "floor": "Terrain",
        "orientation": "Sud",
        "years": "N/A",
        "floor_type": "Terrain nu",
        "features": ["Terrain constructible"],
    },
    {
        "title": "Riad traditionnel rénové",
        "type": "À vendre",
        "price": "1 850 000 TND",
        "location": "Tunis (centre)",
        "details": "380 m² · S+2 + Patio",
        "reference": "IC-2026-010",
        "image_url": "https://picsum.photos/seed/IC-2026-010/1200/800",
        "status": "Disponible",
        "lat": 36.7956,
        "lng": 10.1847,
        "area": 380,
        "rooms": 6,
        "bedrooms": 4,
        "bathrooms": 3,
        "floor": "2 niveaux",
        "orientation": "Ouest",
        "years": "10+ ans",
        "floor_type": "Carrelage",
        "features": ["Patio", "Terrasse", "Rénové"],
    },
    {
        "title": "Villa moderne avec piscine",
        "type": "À louer",
        "price": "3 500 TND / mois",
        "location": "La Marsa",
        "details": "450 m² · S+5 · Piscine chauffée",
        "reference": "IC-2026-011",
        "image_url": "https://picsum.photos/seed/IC-2026-011/1200/800",
        "status": "Disponible",
        "lat": 36.87,
        "lng": 10.32,
        "area": 450,
        "rooms": 7,
        "bedrooms": 5,
        "bathrooms": 4,
        "floor": "Maison",
        "orientation": "Sud-Est",
        "years": "1-5 ans",
        "floor_type": "Marbre",
        "features": ["Piscine chauffée", "Garage", "Jardin"],
    },
    {
        "title": "Appartement neuf avec balcon",
        "type": "À vendre",
        "price": "720 000 TND",
        "location": "Menzah 6",
        "details": "185 m² · S+3 · Balcon 40m²",
        "reference": "IC-2026-012",
        "image_url": "https://picsum.photos/seed/IC-2026-012/1200/800",
        "status": "Disponible",
        "lat": 36.8056,
        "lng": 10.2089,
        "area": 185,
        "rooms": 4,
        "bedrooms": 3,
        "bathrooms": 2,
        "floor": "5ème",
        "orientation": "Est",
        "years": "Moins d'un an",
        "floor_type": "Parquet",
        "features": ["Balcon 40m²", "Ascenseur", "Garage"],
    },
]


class Command(BaseCommand):
    help = (
        "Seed the initial properties (creates only missing records, keyed by "
        "reference; never overwrites existing entries, so admin edits are safe)."
    )

    def handle(self, *args, **options):
        created = 0
        for item in SEED:
            _, was_created = Property.objects.get_or_create(
                reference=item["reference"],
                defaults=item,
            )
            if was_created:
                created += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Done: {created} created, skipped existing. "
                f"Total properties: {Property.objects.count()}."
            )
        )
