# Generated by Django 5.1.6 on 2026-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('À vendre', 'À vendre'), ('À louer', 'À louer')], default='À vendre', max_length=16)),
                ('price', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Réservé', 'Réservé'), ('Vendu', 'Vendu'), ('Loué', 'Loué')], default='Disponible', max_length=32)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('area', models.PositiveIntegerField(blank=True, help_text='Surface area in m²', null=True)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=64)),
                ('orientation', models.CharField(blank=True, max_length=64)),
                ('years', models.CharField(blank=True, max_length=64)),
                ('floor_type', models.CharField(blank=True, max_length=64)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
