# Generated by Django 5.1.6 on 2026-08-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image (stored on the Railway volume). Takes priority over image_url.', null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL, used when no file is uploaded.', max_length=500),
        ),
    ]
