# Generated by Django 5.1.6 on 2026-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_image_alter_property_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom et prénom')),
                ('phone', models.CharField(max_length=32, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom et prénom')),
                ('phone', models.CharField(max_length=32, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('zone', models.CharField(max_length=128, verbose_name='Zone / quartier')),
                ('property_type', models.CharField(blank=True, choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('riad', 'Riad')], max_length=32, verbose_name='Type de bien')),
                ('transaction', models.CharField(choices=[('Vente', 'Vente'), ('Location', 'Location')], default='Vente', max_length=16, verbose_name='Transaction')),
                ('surface', models.CharField(blank=True, max_length=32, verbose_name='Surface (m²)')),
                ('known_from', models.CharField(blank=True, choices=[('search', 'Moteur de recherche'), ('social', 'Réseaux sociaux'), ('referral', 'Recommandation'), ('other', 'Autre')], max_length=32, verbose_name='Comment nous avez-vous connus ?')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': "Demande d'estimation",
                'verbose_name_plural': "Demandes d'estimation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bien immobilier', 'verbose_name_plural': 'Biens immobiliers'},
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salles de bain'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chambres'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='property',
            name='details',
            field=models.CharField(blank=True, help_text='Ex. : 165 m² · S+3', max_length=255, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'équipements, ex. : Piscine, Garage, Jardin", verbose_name='Équipements'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, max_length=64, verbose_name='Étage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Revêtement'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text="Photo importée (stockée sur le volume Railway). Prioritaire sur l'URL.", null=True, upload_to='properties/', verbose_name='Photo (fichier)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, help_text="Utilisée uniquement si aucune photo n'est importée.", max_length=500, verbose_name='Photo (URL externe)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié sur le site'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=128, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='orientation',
            field=models.CharField(blank=True, max_length=64, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(help_text='Ex. : 580 000 TND ou 2 400 TND / mois', max_length=64, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='property',
            name='reference',
            field=models.CharField(max_length=32, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pièces'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Réservé', 'Réservé'), ('Vendu', 'Vendu'), ('Loué', 'Loué')], default='Disponible', max_length=32, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('À vendre', 'À vendre'), ('À louer', 'À louer')], default='À vendre', help_text='À vendre ou à louer.', max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='property',
            name='years',
            field=models.CharField(blank=True, max_length=64, verbose_name='Âge du bien'),
        ),
    ]
